name:                SimpleCardGame
version:             0.1.0.0
github:              "githubuser/SimpleCardGame"
license:             BSD3
author:              "Cuey"
maintainer:          "cueballmania@hotmail.com"
copyright:           "2023 Cuey"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/SimpleCardGame#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- random
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  SimpleCardGame-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SimpleCardGame
    when:
    - condition: false
      other-modules: Paths_SimpleCardGame

tests:
  SimpleCardGame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SimpleCardGame
